### ISSUE TITLE
Error beim Client Start

### ISSUE THREAD

**Issue by ChrisX1809** [BOSWatch/BW3-Core#122]
Hallo,

habe mich durch das install Script geschlagen und alle relevanten Sachen installiert. Der Server lässt sich starten und der Client connectet auch. Allerdings erhalte ich beim Client einen Fehler, den ich nicht deuten kann, es heisst:

```
08.06.2024 23:33:01,909 - sdrInput        [ERROR   ] error in sdr input routine
Traceback (most recent call last):
  File "/opt/boswatch3/boswatch/inputSource/sdrInput.py", line 43, in _runThread
    sdrProc.start()
  File "/opt/boswatch3/boswatch/processManager.py", line 53, in start
    self._processHandle = subprocess.Popen(self._args,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/pi/rtl-sdr'
Exception in thread inputThread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/boswatch3/boswatch/inputSource/sdrInput.py", line 69, in _runThread
    mmProc.stop()
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stop'
 error in sdr input routine
```

Was mache ich falsch?

**Comment by Schrolli91** [comment]
Siehe `PermissionError: [Errno 13] Permission denied: '/home/pi/rtl-sdr'`
Hier scheinen Rechte zu fehlen um das SDR Device zu öffnen.
Mit welchem User führst du das Script aus?

**Comment by ChrisX1809** [comment]
Hey,
ich bekomme es nicht zum laufen. Jetzt startet der Server nicht mehr:

```
21.06.2024 23:14:13,971 - bw_server       [DEBUG   ]
21.06.2024 23:14:13,971 - bw_server       [DEBUG   ] ######################## NEW LOG ############################
21.06.2024 23:14:13,972 - bw_server       [DEBUG   ] BOSWatch server has started ...
21.06.2024 23:14:13,972 - bw_server       [DEBUG   ] Import python modules
21.06.2024 23:14:13,978 - bw_server       [DEBUG   ] - argparse
21.06.2024 23:14:13,979 - bw_server       [DEBUG   ] - queue
21.06.2024 23:14:13,979 - bw_server       [DEBUG   ] - time
21.06.2024 23:14:13,979 - bw_server       [DEBUG   ] Import BOSWatch modules
21.06.2024 23:14:14,030 - configYaml      [DEBUG   ] - boswatch.configYaml loaded
21.06.2024 23:14:14,032 - server          [DEBUG   ] - boswatch.network.server loaded
21.06.2024 23:14:14,034 - packet          [DEBUG   ] - boswatch.packet loaded
21.06.2024 23:14:14,042 - version         [DEBUG   ] - boswatch.utils.version loaded
21.06.2024 23:14:14,042 - header          [DEBUG   ] - boswatch.utils.header loaded
21.06.2024 23:14:14,044 - broadcast       [DEBUG   ] - boswatch.network.broadcast loaded
21.06.2024 23:14:14,046 - router          [DEBUG   ] - boswatch.router.router loaded
21.06.2024 23:14:14,047 - route           [DEBUG   ] - boswatch.router.route loaded
21.06.2024 23:14:14,047 - routerManager   [DEBUG   ] - boswatch.router.routerManager loaded
21.06.2024 23:14:14,048 - misc            [DEBUG   ] - boswatch.utils.misc loaded
21.06.2024 23:14:14,049 - header          [DEBUG   ]     ____  ____  ______       __      __       __       _____
21.06.2024 23:14:14,049 - header          [DEBUG   ]    / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_     |__  /
21.06.2024 23:14:14,049 - header          [DEBUG   ]   / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \     /_ <
21.06.2024 23:14:14,049 - header          [DEBUG   ]  / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /   ___/ /
21.06.2024 23:14:14,050 - header          [DEBUG   ] /_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/   /____/
21.06.2024 23:14:14,050 - header          [DEBUG   ]                 German BOS Information Script
21.06.2024 23:14:14,050 - header          [DEBUG   ]                      by Bastian Schroll
21.06.2024 23:14:14,050 - header          [DEBUG   ]
21.06.2024 23:14:14,051 - header          [DEBUG   ] BOSWatch and environment information
21.06.2024 23:14:14,051 - header          [DEBUG   ] - Client version:   3.0.0
21.06.2024 23:14:14,051 - header          [DEBUG   ] - Server version:   3.0.0
21.06.2024 23:14:14,052 - header          [DEBUG   ] - Branch:           develop
21.06.2024 23:14:14,052 - header          [DEBUG   ] - Release date:     01.01.2019
21.06.2024 23:14:14,052 - header          [DEBUG   ] - Python version:   3.11.2
21.06.2024 23:14:14,053 - header          [DEBUG   ] - Python build:     ('main', 'Mar 13 2023 12:18:29')
21.06.2024 23:14:14,053 - header          [DEBUG   ] - System:           Linux
21.06.2024 23:14:14,065 - header          [DEBUG   ] - OS Version:       Linux-6.6.20+rpt-rpi-v8-aarch64-with-glibc2.36
21.06.2024 23:14:14,065 - header          [DEBUG   ]
21.06.2024 23:14:14,075 - configYaml      [DEBUG   ] load config file from: /opt/boswatch3/boswatch/../config/opt/boswatch3/s               erver.yaml
21.06.2024 23:14:14,076 - configYaml      [ERROR   ] config file not found: /opt/boswatch3/boswatch/../config/opt/boswatch3/s               erver.yaml
21.06.2024 23:14:14,076 - bw_server       [CRITICAL] cannot load config file
```


Ich rufe den Start folgendermaßen auf:

` sudo python3 bw_server.py -c opt/boswatch3/server.yaml `

Gibt es eine Möglichkeit die Doku für Watch3 wieder zu veröffentlichen?

**Comment by Schrolli91** [comment]
` /opt/boswatch3/boswatch/../config/opt/boswatch3/s               erver.yaml`
Wie kommen die Leerzeichen in den Pfad?
